# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "about"
  url = "/about"
  weight = 10

[[main]]
  name = "about us"
  parent = "about"
  url = "/about"
  weight = 11

[[main]]
  name = "people"
  parent = "about"
  url = "/people"
  weight = 12

[[main]]
  name = "projects"
  parent = "about"
  url = "/project"
  weight = 13

[[main]]
  name = "media"
  parent = "about"
  url = "/media"
  weight = 14

[[main]]
  name = "news"
  url = "/post"
  weight = 20

[[main]]
  name = "publications"
  url = "/publication"
  weight = 30

[[main]]
  name = "geospatial resources"
  weight = 50

[[main]]
  name = "our data+code"
  parent = "geospatial resources"
  url = "/data-code"
  weight = 51

[[main]]
  name = "list of journals"
  parent = "geospatial resources"
  url = "/post/2020/07/06/geospatial-and-urban-data-science-journals/"
  weight = 52

[[main]]
  name = "roofpedia"
  parent = "geospatial resources"
  url = "/project/roofpedia/"
  weight = 53

[[main]]
  name = "open building data"
  parent = "geospatial resources"
  url = "/project/ogbd/"
  weight = 54

[[main]]
  name = "open data SG"
  parent = "geospatial resources"
  url = "/post/2020/06/24/guide-for-open-urban-data-in-singapore/"
  weight = 55

[[main]]
  name = "opportunities"
  weight = 80

[[main]]
  name = "why us"
  parent = "opportunities"
  url = "/opportunities/why-us"
  weight = 81

[[main]]
  name = "openings"
  parent = "opportunities"
  url = "/opportunities/vacancies"
  weight = 82

[[main]]
  name = "phd"
  parent = "opportunities"
  url = "/opportunities/phd"
  weight = 83

[[main]]
  name = "NUS courses"
  parent = "opportunities"
  url = "/opportunities/teaching"
  weight = 84

[[main]]
  name = "student initiated projects"
  parent = "opportunities"
  url = "/opportunities/student-projects"
  weight = 85

[[main]]
  name = "fellowships"
  parent = "opportunities"
  url = "/opportunities/fellowships"
  weight = 86


[[main]]
  name = "contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
