markup:
  _merge: deep
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes: ['']
outputFormats:
  headers:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  redirects:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
module:
  hugoVersion:
    min: '0.87.0'
    extended: true
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
params:
  theme: old_minimal
  font: classic
  date_format: '2006-01-02'
  time_format: '15:04'
  address_format: en-us
